server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/commentDb?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: comment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka