server:
  port: 9000

eureka:
  client:
    service-url:
#      defaultZone: http://eureka:password@localhost:8761/eureka
      defaultZone: http://discovery-server:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-social-realm
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/post/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**

