server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: postDb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka